### ISSUE TITLE
Readiness probe authentication problem

### ISSUE THREAD

**Issue by ThickDrinkLots** [spotahome/redis-operator#291] opened 2020-10-06 08:08 UTC
### Expected behaviour

working redis cluster

### Actual behaviour

When authentication is enabled readiness probes have problem with performing their checks on rfr-redisfailover-N nodes. On every node I get:
```
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.  
Warning: AUTH failed
```
But when I connect to node with `rsh` I can "log in" to redis executing for example:
```
$ redis-cli -a <PASSWORD> info replication
```
and I get command output and only the first warning (that putting password on cli is not safe)
I'm using the same password in both cases, of course.

### Steps to reproduce the behaviour

* on redisfailover.yaml I have:
```
[...]
spec:
  sentinel:
    [...]
  redis:
    replicas: 3
    [..]
  auth:
    secretPath: redis-auth
```
* I deploy redis cluster by running:
```
oc -n <namespace> create -f ./redisfailover.yaml
```
### Environment

How are the pieces configured?
* Redis Operator version: release 1.0.0
* Kubernetes version: Openshift v3.11 with kubernetes v1.11
* Kubernetes configuration used (eg: Is RBAC active?)

**Comment by bbobrov** [comment] 2020-10-12 08:09
I can confirm this issue. I think it was caused by https://github.com/spotahome/redis-operator/pull/235

**Comment by StephanSchultchenFactset** [comment] 2020-10-14 20:37
i have the same problem, i also tried to use 0.5.8 version of the operator, which refuses to even start. anyone who got this operator running?

**Comment by bbobrov** [comment] 2020-10-14 20:43
I managed to get it running by creating a password. There is a description how to do it in README.md
________________________________

**Comment by StephanSchultchenFactset** [comment] 2020-10-14 21:01
nope even when setting a password, as described in the readme, i still get the readiness probe error:

"Readiness probe failed: unespected Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe. "

**Comment by StephanSchultchenFactset** [comment] 2020-10-14 21:20
in the log of the operator i can see this:

time="2020-10-14T21:18:51Z" level=error msg="Error processing default/redisfailover-123: ERR invalid password" controller=redisfailover operator=redis-operator src="generic.go:224"

it seems like the operator is not picking up the password that has been set for redis :-/

**Comment by bbobrov** [comment] 2020-10-15 08:39
The issue with the warning has been fixed in https://github.com/spotahome/redis-operator/pull/257. Could you please try using the master branch and check if the issue is still there? You might need to rebuild the operator image, publish it somewhere and use in the helm chart - https://github.com/spotahome/redis-operator/blob/master/docker/app/Dockerfile

**Comment by StephanSchultchenFactset** [comment] 2020-10-15 11:03
i will try later,

but will this also address the error i have seen in the operator log?

**Comment by StephanSchultchenFactset** [comment] 2020-10-16 08:58
build not working.

i cloned the this git repo and executed 'docker build docker/app/':

```
Sending build context to Docker daemon  2.048kB
Step 1/10 : FROM golang:1.13-alpine
 ---> 5863598a981a
Step 2/10 :  WORKDIR /go/src/github.com/spotahome/redis-operator
 ---> Using cache
 ---> 9b96876b273b
Step 3/10 : COPY . .
 ---> Using cache
 ---> 8a20462d78b2
Step 4/10 : RUN ./scripts/build.sh
 ---> Running in a36c42f0db8f
/bin/sh: ./scripts/build.sh: not found
The command '/bin/sh -c ./scripts/build.sh' returned a non-zero code: 127
```

**Comment by dejwsz** [comment] 2020-10-20 07:02
It would be good to fix this issue, I had the same problem.

**Comment by XBeg9** [comment] 2020-11-04 09:45
having the same issue, any updates here?

**Comment by bbobrov** [comment] 2020-11-04 10:02
> build not working.
> 
> i cloned the this git repo and executed 'docker build docker/app/':

Try building the latest operator with `make` (it might be useful to read the `Makefile` to understand what it does). It will also create `bin/linux/redis-operator`, that can use to build an image with.

**Comment by jessebye** [comment] 2021-04-01 22:12
We have this problem:

```
Readiness probe failed: Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe. 
```

But no errors logged by the operator. Seems like there is some issue with using auth and this operator?

**Comment by Zeka13** [comment] 2021-04-12 10:29
@jessebye this repo is dead

**Comment by jessebye** [comment] 2021-04-12 15:30
@Zeka13 yes, I've been realizing that. We switched to https://github.com/OT-CONTAINER-KIT/redis-operator and so far it has been good. Actively maintained too.

**Closed** 2022-01-13 09:59 UTC
